name = "cf-cl-lin-2"
main = "src/worker.js"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "twitter_metrics"
database_id = "694de08e-72d6-43c2-8b07-f52bc903563d"

[vars]
TWITTER_PUBLIC_URL = "https://x.com/jilvaa198175"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true
